directory = File.dirname(__FILE__)
require "#{directory}/../../Vagrantfile.core"

Vagrant.configure('2') do |config|
  config.ssh.password = 'vagrant'
  config.ssh.forward_x11 = true
  gusztavvargadr_workstations_vm config, directory, 'work'
end
